var strainList = [
    {
        "name": "Cherry Punch",
        "type": ["sativa"],
        "grow": ["indoors", "outdoors"],
        "description": "Some Purple. Less “punch” nose than purple punch. This strain is ideal for those seeking relief from anxiety and stress.", 
        "photo": ["cherrypunch-tb.jpg", "cherry.jpg"],
        "growtime": "8-9",
        "yield": "high",
        "thc": "22-27%",
        "cbd": "<2%",
        "available": false,
        "section": "featured"
    },
    {
        "name": "Cereal Milk",
        "type": ["sativa", "indica"],
        "grow": ["indoors"],
        "description": "Mostly purple. Pungent Gassy smell. Euphoric, calming and energizing state. Soothing the body while enhancing creativity.",
        "photo": ["cerealmilk-tb.jpg", "cerealmilk.jpg"],
        "growtime": "9",
        "yield": "medium",
        "thc": "24-31%",
        "cbd": "<2%",
        "available": true,
        "section": "featured"
    },
    {
        "name": "Purple Punch",
        "type": ["indica"],
        "grow": ["indoors"],
        "description": "Extreme Purple and Trichome Production - Helps patients with managing nausea, stress, minor body aches, and sleeplessness.",
        "photo": ["purplepunch-tb.jpg", "purplepunch4.jpg"],
        "growtime": "7",
        "yield": "high",
        "thc": "19-24%",
        "cbd": "<2%",
        "available": true,
        "section": "featured"
    },
    {
        "name": "Project X",
        "type": ["sativa", "indica"],
        "grow": ["indoors", "outdoors"],
        "description": "Requires more deleafing, High Trichome Production - creative effects that are happy and uplifting",
        "photo": ["projectx-tb.jpg", "projectX52.jpg"],
        "growtime": "9",
        "yield": "high",
        "thc": "26-31%",
        "cbd": "<2%",
        "available": false,
        "section": "featured"
    },
    {
        "name": "Sunday Driver",
        "type": ["indica"],
        "grow": ["indoors", "outdoors"],
        "description": "Some purple. Funky smell. Full relaxation. Euphoric effects followed by full-body relaxation.",
        "photo": ["sundaydriver-tb.jpg", "sundaydriver2.jpg"],
        "growtime": "8-9",
        "yield": "high",
        "thc": "23-27%",
        "cbd": "<2%",
        "available": true,
        "section": "featured"
    },
    {
        "name": "Lava Cake",
        "type": ["indica"],
        "grow": ["indoors", "outdoors"],
        "description": "Dense Buds. Genetics hold relief for chronic pain, stress and anxiety.",
        "photo": ["lavacake01-tb.jpg", "lavacake3.jpg"],
        "growtime": "8",
        "yield": "medium",
        "thc": "25-31%",
        "cbd": "<2%",
        "available": true,
        "section": "featured"
    },
    {
        "name": "White Tahoe Cookies",
        "type": ["sativa"],
        "grow": ["indoors", "outdoors"],
        "description": "Larger nugs than traditional cookies with less color.",
        "photo": ["lavacake-tb.jpg", "lavacake3.jpg"],
        "growtime": "8-9",
        "yield": "high",
        "thc": "26-32%",
        "cbd": "<2%",
        "available": true,
        "section": "featured"
    },
    {
        "name": "Girl Scout Cookies",
        "type": ["sativa"],
        "grow": ["indoors", "outdoors"],
        "description": "Smaller nug size yet very dense buds.",
        "photo": ["lavacake-tb.jpg", "lavacake3.jpg"],
        "growtime": "8-9",
        "yield": "high",
        "thc": "26-29%",
        "cbd": "<2%",
        "available": true,
        "section": "featured"
    }
]